# application configuration

# the websocket endpoint for a language connector sidecar
network.connector: 'ws://127.0.0.1:8090/ws/lang'

#
# language.pack.key should point to an environment variable containing a secret key for connection to
# a language connector. If the environment variable does not exist, the system will get the secret key
# from the temporary local file system at /tmp/config/lang-api-key.txt
#
language:
  pack:
    key: 'LANGUAGE_PACK_KEY'

work:
  directory: '/tmp/python'

log:
  directory: '/tmp/log'
  level: INFO
  # for cloud native, do not configure log.filename
  # comment it out, leave it blank or set it to "none"
  #
  # If given, the file path will be constructed as follows:
  # {log.directory}/{log.filename}.log
  #
  filename: none

# max number of threads in a python 'futures' thread pool
max.threads: 250
