# application configuration

# the websocket endpoint for a language connector sidecar
network.connector: 'ws://127.0.0.1:8090/ws/lang'

# the environment variable name for the API key to connect to a language connector
language:
  pack:
    key: 'LANGUAGE_PACK_KEY'

work:
  directory: '/tmp/python'

log:
  level: INFO
  # for cloud native, do not configure log.filename
  # comment it out, leave it blank or set it to "none"
  #
  # If given, the file path will be constructed as follows:
  # {work.directory}/{log.filename}.log
  #
  filename: none

# max number of threads in a python 'futures' thread pool
max.threads: 250
